
<template>
  <div>
    <v-container fluid>
      <v-row >
        <!-- Sidebar Section -->
        <v-col cols="12" md="2" class="sideBar">
            <v-row>
              <v-col cols="12" sm="12">
                <div class="control-panel-font">Company Overview</div>
              </v-col>
            </v-row>
            <v-row>
              <v-col cols="12" sm="12">
                <v-select
                    :items="categories.values"
                    label="Select a category"
                    dense
                    v-model="categories.selectedValue"
                    @change="changeCategory"
                ></v-select>
              </v-col>
            </v-row>
          <!-- Add space here -->
          <div style="height: 400px;"></div>

            <v-row>
              <v-col cols="12" sm="12">
                <div class="control-panel-font">Profit View of Company</div>
              </v-col>
            </v-row>
            <v-row>
              <v-col cols="12" sm="12">
                <v-select
                    :items="companies.values"
                    item-title="name"
                    item-value="id"
                    label="Select a company"
                    dense
                    v-model="companies.selectedValue"
                    @change="changeCompany"

                ></v-select>
                <v-select
                    :items="algorithm.values"
                    label="Select an algorithm"
                    dense
                    v-model="algorithm.selectedValue"
                    @change="changeAlgorithm"
                ></v-select>
              </v-col>
            </v-row>
        </v-col>
        <!-- Main Content Section -->
        <v-col cols="12" md="10" style="height: 100vh">
          <!-- First Row -->
          <v-row style="height: 50%">
            <v-col cols="12" md="6" style="height: 100%">
              <v-card style="height: 100%">
                <ScatterPlot :key="scatterPlotId"
                             :selectedCategory="categories.selectedValue"
                             @changeCurrentlySelectedCompany="changeCurrentlySelectedCompany"
                />
                <div class="appendix">* Click on the data point to see the company profit below.</div>
              </v-card>
            </v-col>
            <v-col cols="12" md="6" style="height: 100%">
               <v-card style="height: 100%">
                 <LineBarPlot  :key="lineBarPlotId"
                               :selectedCategory="categories.selectedValue"
                               :selectedCompany="companies.selectedValue"
                 />
                 <div class="appendix">* Selected company is highlighted.</div>
                </v-card>
            </v-col>
        </v-row>
          <!-- Second Row -->
          <v-row style="height: 50%">
          <v-col cols="12" md="6" style="height: 100%">
            <v-card style="height: 100%">
              <LinePlot :key="linePlotId"
                      :selectedCompany="companies.selectedValue"
                      :selectedAlgorithm="algorithm.selectedValue"/>
            </v-card>
          </v-col>
            <v-col cols="12" md="6" style="height: 100%">
              <v-card
                  style="height: 100%"
                  color=#6c6fbe
              >
                <div class="text-overline mb-1">
                  Information is generated by GROQ
                </div>
                <!-- poem-->
                <v-card-title>
                  Poem
                </v-card-title>
                <PoemLLM :selectedCompany="companies.selectedValue" />
                <!-- Add space here -->
                <div style="height: 50px;"></div>
                <!-- evaluation-->
                <v-card-title>
                  Evaluation
                </v-card-title>
                <EvaluationLLM :selectedCompany="companies.selectedValue" />
              </v-card>
            </v-col>

          </v-row>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>


<script>
import ScatterPlot from './ScatterPlot';
import LinePlot from './LinePlot';
import LineBarPlot from './LineBarPlot';
import PoemLLM from "./Poem.vue";
import EvaluationLLM  from "./Evaluation.vue";
export default {
  components: {ScatterPlot, LinePlot, LineBarPlot, PoemLLM, EvaluationLLM},
  data: () => ({
    scatterPlotId: 0,
    linePlotId: 0,
    lineBarPlotId: 0,
    categories: {
      values: ['All', 'tech', 'health', 'bank'],
      selectedValue: 'All'
    },

    companies: {
      values: [{id: 1, name: "alphabet", category: "tech"},
        {id: 2, name: "apple", category: "tech"},
        {id: 3, name: "amazon", category: "tech"},
        {id: 4, name: "microsoft", category: "tech"},
        {id: 5, name: "meta", category: "tech"},
        {id: 6, name: "united health", category: "health"},
        {id: 7, name: "johnson and johnson", category: "health"},
        {id: 8, name: "pfizer", category: "health"},
        {id: 9, name: "cvs health", category: "health"},
        {id: 10, name: "mckesson", category: "health"},
        {id: 11, name: "ubs", category: "bank"},
        {id: 12, name: "credit suisse", category: "bank"},
        {id: 13, name: "jp morgan", category: "bank"},
        {id: 14, name: "goldman sachs", category: "bank"},
        {id: 15, name: "bank of america", category: "bank"}],
      selectedValue: 1 //default value
    },
    algorithm: {
      values: ['none', 'random', 'regression'],
      selectedValue: 'none'
    }
  }),
  methods: {
    changeCategory() {
      this.scatterPlotId += 1
      this.lineBarPlotId += 1
    },
    changeCompany() {
      this.linePlotId += 1
      this.lineBarPlotId += 1
    },
    changeAlgorithm() {
      this.linePlotId += 1
    },
    changeCurrentlySelectedCompany(companyId) {
      this.companies.selectedValue = companyId
      this.changeCompany()
    }
  }
}

</script>

<style scoped>
.control-panel-font {
  font-family: "Open Sans", verdana, arial, sans-serif;
  align-items: center;
  font-size: 15px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
  display: flex;
  font-weight: 600;
  height: 40px;
  color:black;
}
.sideBar {
  border-right: 1px solid rgba(0, 0, 0, 0.1);
  padding-left: 17px;
  height: calc(100vh - 50px);
  background: linear-gradient(to bottom, #ffffff, #6c6fbe);
}
.appendix {
  position: absolute;
  bottom: 10px;
  right: 10px;
  color: gray;
  font-size: 12px;
}
</style>
